LANGUAGES = {
    'ru': {
        'welcome': "Добро пожаловать в Onlive Twilight Convert bot! 🌍💱\n\nДля конвертации валюты просто введите сумму и код валюты. Например:\n100 USD\n5000 RUB\n750 EUR\n\nВы также можете использовать этот бот inline в любом чате, набрав @onlive_twilight_bot, за которым следует сумма и валюта.\n\nИспользуйте кнопки ниже для получения дополнительной информации или настройки бота.",
        'help': "🤖 Как использовать бота:\n\n1. Для простой конвертации введите сумму и код валюты, например: 100 USD\n2. Для конвертации между двумя конкретными валютами используйте формат: 100 USD EUR\n3. Вы можете использовать бота inline в любом чате, набрав @onlive_twilight_bot 100 USD\n\nПоддерживаемые валюты: ",
        'feedback': "📬 Обратная связь:\n\nМы всегда рады вашим предложениям и замечаниям!\nCвяжитесь со мной в Telegram: @onswix",
        'settings': "Выберите раздел настроек:",
        'currencies': "Выберите валюты:",
        'cryptocurrencies': "Выберите криптовалюты:",
        'language': "Выберите язык:",
        'save_settings': "Настройки сохранены!",
        'invalid_input': "Неверный ввод. Пожалуйста, введите сумму и код валюты, например, '100 USD' или '100 USD EUR'.",
        'error': "Произошла ошибка. Пожалуйста, попробуйте снова.",
        'fiat_currencies': "Фиатные валюты:",
        'cryptocurrencies_output': "Криптовалюты:",
        'back': "Назад",
        'help_button': "❓ Помощь",
        'news_button': "🗞 Новости",
        'feedback_button': "💭 Обратная связь",
        'settings_button': "⚙️ Настройки",
        'save_button': "Сохранить настройки",
        'back_to_settings': "Назад к настройкам",
        'forward': "Вперёд",
        'stats_title': "📊 Статистика бота:",
        'total_users': "👥 Общее количество пользователей:",
        'active_users': "🔵 Активных пользователей сегодня:",
        'new_users': "🆕 Новых пользователей сегодня:",
        'no_currencies_selected': "Валюты не выбраны",
        'select_currencies_message': "Пожалуйста, выберите валюты в настройках",
        'select_currencies_full_message': "Вы не выбрали ни одной валюты. Пожалуйста, перейдите в настройки бота, чтобы выбрать валюты для конвертации.",
        'conversion_result': "Результат конвертации",
        'number_too_large': "Число слишком большое для обработки.",
        'about_button': "О боте",
        'about_message': "Информация о боте Onlive Twilight Convert",
        'current_version': "Текущая версия:",
        'view_changelog': "Посмотреть список изменений",
    },
    'en': {
        'welcome': "Welcome to Onlive Twilight Convert bot! 🌍💱\n\nTo convert currency, simply enter an amount and currency code. For example:\n100 USD\n5000 RUB\n750 EUR\n\nYou can also use this bot inline in any chat by typing @onlive_twilight_bot followed by an amount and currency.\n\nUse the buttons below for more information or to configure the bot.",
        'help': "🤖 How to use the bot:\n\n1. For simple conversion, enter an amount and currency code, e.g.: 100 USD\n2. To convert between two specific currencies, use the format: 100 USD EUR\n3. You can use the bot inline in any chat by typing @onlive_twilight_bot 100 USD\n\nSupported currencies: ",
        'feedback': "📬 Feedback:\n\nWe always appreciate your suggestions and comments!\nContact me on Telegram: @onswix",
        'settings': "Choose a settings section:",
        'currencies': "Select currencies:",
        'cryptocurrencies': "Select cryptocurrencies:",
        'language': "Select language:",
        'save_settings': "Settings saved!",
        'invalid_input': "Invalid input. Please enter an amount and currency code, e.g., '100 USD' or '100 USD EUR'.",
        'error': "An error occurred. Please try again.",
        'fiat_currencies': "Fiat currencies:",
        'cryptocurrencies_output': "Cryptocurrencies:",
        'back': "Back",
        'help_button': "❓ Help",
        'news_button': "🗞 News",
        'feedback_button': "💭 Feedback",
        'settings_button': "⚙️ Settings",
        'save_button': "Save settings",
        'back_to_settings': "Back to settings",
        'forward': "Next",
        'stats_title': "📊 Bot Statistics:",
        'total_users': "👥 Total number of users:",
        'active_users': "🔵 Active users today:",
        'new_users': "🆕 New users today:",
        'no_currencies_selected': "No currencies selected",
        'select_currencies_message': "Please select currencies in settings",
        'select_currencies_full_message': "You haven't selected any currencies. Please go to bot settings to select currencies for conversion.",
        'conversion_result': "Conversion Result",
        'number_too_large': "The number is too large to process.",
        'about_button': "About",
        'about_message': "About Onlive Twilight Convert bot",
        'current_version': "Current version:",
        'view_changelog': "View changelog",
    }
}